  404-page-implementation[m
  app-router-implementation[m
* [32mcomponent-template[m
  develop[m
  main[m
  main-view_adaptive[m
  release/login-registration-main[m
  signin-confirmation-message[m
  token-handling[m
  unit-test-implementation-vol2[m
  unit-tests-implementation[m
  [31mremotes/origin/404-page-implementation[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/app-router-implementation[m
  [31mremotes/origin/create-readme[m
  [31mremotes/origin/develop[m
  [31mremotes/origin/fix-issues[m
  [31mremotes/origin/gh-pages[m
  [31mremotes/origin/integration-commercetools[m
  [31mremotes/origin/links-fix[m
  [31mremotes/origin/login-page[m
  [31mremotes/origin/login-page-func[m
  [31mremotes/origin/main[m
  [31mremotes/origin/main-page-links[m
  [31mremotes/origin/main-view[m
  [31mremotes/origin/main-view_adaptive[m
  [31mremotes/origin/prettier-env[m
  [31mremotes/origin/registration-page[m
  [31mremotes/origin/registration-page-address-upd[m
  [31mremotes/origin/registration-page-validation[m
  [31mremotes/origin/release/login-registration-main[m
  [31mremotes/origin/repository-setup[m
  [31mremotes/origin/signin-confirmation-message[m
  [31mremotes/origin/sprint2_integration-commercetools[m
  [31mremotes/origin/sprint3_catalog-product-profile[m
  [31mremotes/origin/token-cache[m
  [31mremotes/origin/token-handling[m
  [31mremotes/origin/unit-test-implementation-vol2[m
  [31mremotes/origin/unit-tests-implementation[m
